### ISSUE TITLE
Crash due to undefined type

### ISSUE THREAD

**Issue by fuhlig1** [HeavyIonAnalysis/AnalysisTreeQA#10]
In the code the data type **uint** is used a several places. I assume that an **unsigned int** is meant here. This type **uint** must be a typedef which somehow is implicitly included by one of the header files. I was not able to find out were uint is really defined.

When compiling the code on macosx with newer FairSoft/FairRoot versions the compilation crashes with the following error

```
/Users/uhlig/software/fair/cbm/cbmroot_git/external/AnalysisTreeQA/src/EntryConfig.hpp:74:31: error: unknown type name 'uint'
  ANALYSISTREE_ATTR_NODISCARD uint GetNdimentions() const { return axes_.size(); }
```

With the specific setup the type **uint** is suddenly undefined. 

The easiest solution would be to change uint to unsigned int. Please check if you could fix the issue.
The same problem also appears in the code of AnalysisTree.

**Comment by viktorklochkov** [comment]
Dear @fuhlig1!

Thanks for reporting! Should be fixed with

https://github.com/HeavyIonAnalysis/AnalysisTreeQA/commit/614296ddc1ba638dd95ce05f252c3f56fd31a796

I will merge corresponding changes also to AnalysisTree soon

Cheers,
Viktor
