### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by viktorklochkov** [HeavyIonAnalysis/AnalysisTreeQA#5]
> cbmmac004:build uhlig$ more /tmp/cbmroot/build/external/ANALYSISTREEQA-prefix/src/ANALYSISTREEQA-stamp/ANALYSISTREEQA-build-err.log
> Cloning into 'Cuts_src'...
> Already on 'master'
> CMake Error at /tmp/cbmroot/build/external/ANALYSISTREEQA-prefix/src/ANALYSISTREEQA-build/external/Cuts_build/_deps/analysistree-src/CMakeLists.txt:43 (find_package):
>   By not providing "FindROOT.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "ROOT", but
>   CMake did not find one.
>
>   Could not find a package configuration file provided by "ROOT" with any of
>   the following names:
>
>     ROOTConfig.cmake
>     root-config.cmake
>
>   Add the installation prefix of "ROOT" to CMAKE_PREFIX_PATH or set
>   "ROOT_DIR" to a directory containing one of the above files.  If "ROOT"
>   provides a separate development package or SDK, be sure it has been
>   installed.
>
>
> make[5]: *** [Cuts_Ext-prefix/src/Cuts_Ext-stamp/Cuts_Ext-configure] Error 1
> make[4]: *** [CMakeFiles/Cuts_Ext.dir/all] Error 2
> make[3]: *** [all] Error 2

**Comment by eugene274** [comment]
See:
https://git.cbm.gsi.de/pwg-c2f/analysis/cuts/-/commit/bb39745868aef15b363a2b24bfd7024b13f49a51

Should work now.

**Comment by fuhlig1** [comment]
Hi @viktorklochkov 

I think the underlying problem is that you use AnalysisTree and Cuts as external projects inside AnalysisTreeQA but both of them use the master branch. This is problematic since even if we use a fixed version of AnalysisTree in CbmRoot we get behind the scenes indirect changes. On the other side we already have installed the AnalysisTree, why do we need another and maybe incompatible version?

**Comment by fuhlig1** [comment]
Hi @viktorklochkov 

the problems appear with the changes @eugene274 did yesterday in the cuts repository (https://git.cbm.gsi.de/pwg-c2f/analysis/cuts). If I fix the version of the cuts used in AnalysisTreeQA to 7b82b867a18cd0acd6719d0b121bee12fb83e710 from August 13 the compilation works again without any problems.

In my opinion whenever you used external projects you should fix the used version to a hash or at least a tag. If you use master everything can happen.

**Comment by eugene274** [comment]
Hi @fuhlig1!

That was me who broke compatibility of AnalysisTreeQA and AnalysisTreeCuts by adding new functionality.
Now I'm quickly introducing versioning and few switches in the CMake to preserve backward compatibility.

**Comment by fuhlig1** [comment]
Let's discuss next week after the collaboration meeting how to proceed and which versions to use for CbmRoot. For the time being I disabled the compilation of AnalysisTreeQA inside CbmRoot.

**Comment by eugene274** [comment]
@viktorklochkov 
There is a thing to discuss to avoid such situations in future.

Conceptually cuts are mutable objects that are changing very often by the end-user. And now we have cuts in the form of header inserted in the *compiled* code.

I think, we must:

* separate user space (folder `tasks/`) from the rest of distribution by on/off switch in CMake
* deliver cuts to QA in a different way
